# Impontando numpy

In [1]:
import numpy as np

# Data types and attributes

## El principal tipo de dato de NumPy es ndarray.
Todo lo que usemos en numpy va a ser un ndarray (n dimensional array)

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.0]
               ,[4,5,6.5]])

a3 = np.array([[[1,2,3]
                ,[4,5,6]
                ,[7,8,9]]
               ,[[10,11,12]
                ,[13,14,15]
                ,[16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](anatomia-de-nparray.png)

In [7]:
# Con shape vemos la forma, la cantidad de elementos en cada una de sus dimensiones
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# Con ndim vemos el numero de dimenciones del ndarray
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
# Con dtype vemos el tipo de los elementos que contiene
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
# size nos dice la cantidad de elementos totales en nuestro array
a1.size, a2.size, a3.size

(3, 6, 18)

# IMPORTANTE!!! todo se trabaja con ndarray.
Los tipos de elementos adentro puede cambiar pero las manipulaciones se hacen a los ndarrays.

## Ej: Create a DataFrame from a NumPy array
Por debajo de pandas funciona numpy. Por lo que se pueden representar los ndarray con formato con pandas

In [13]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating arrays

In [14]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [15]:
# NOTA con Shift+Tab le dice q jupyter que habra el docstring de la funcion
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[2, 6, 1, 1, 6],
       [8, 3, 2, 2, 2],
       [1, 1, 2, 7, 5]])

In [20]:
np.random.random(size=(3,5))

array([[0.311282  , 0.69088599, 0.03949536, 0.90748338, 0.79004119],
       [0.31409142, 0.06224293, 0.53605327, 0.628305  , 0.54765637],
       [0.36313075, 0.88962979, 0.41680417, 0.64840412, 0.41803275]])

In [21]:
random_array_3 = np.random.rand(3,5)
random_array_3

array([[0.46291327, 0.47255273, 0.14197065, 0.61142724, 0.23313538],
       [0.78740318, 0.84540987, 0.02076253, 0.73369748, 0.92234754],
       [0.29569827, 0.03060901, 0.29992896, 0.64657092, 0.69444639]])

### Los numeros random de np son pseudo-random. Si le seteamos una semilla podemos generar numeros aleatorios reproducibles. Por si queremos reproducir las pruebas con los mismos numeros

In [22]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

# 3. Viewing arrays and matrices

In [23]:
# Para encontrar los numeros unicos en un array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a1

array([1, 2, 3])

In [25]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a1[0]

1

In [28]:
a2[0]

array([1., 2., 3.])

In [29]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Se puede usar slicing con arrays

In [30]:
# Si quiero los primeros dos elementos de linea, columna, array
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [31]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [32]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

### Numpy arma los arrays de afuera para adentro. 
#### El la primer forma (2) sera el primer corchete -> habra dos elementos que contengan la cantidad de elementos que vengan en el siguiente campo (3).
#### El de mas a la derecha sera la dimension del elemento mas interno. En este caso un array de 5 numeros.

In [33]:
# Como obtengo los primeros 4 numeros del array mas interno:
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

# Manipulating and compearing arrays

### Arithmetic

In [34]:
a1

array([1, 2, 3])

In [35]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [36]:
# SUMA
a1 + ones

array([2., 3., 4.])

In [37]:
# RESTA
a1 - ones

array([0., 1., 2.])

In [38]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [39]:
# MULTIPLICACION
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python

In [ ]:
# How can you reshape a2 to be compatible with a3?
# Search: how to reshape numpy array?
a5 = np.reshape(a2,(2,3,3))

In [ ]:
# Division
a1 / ones

In [ ]:
# Floor division removes the decimals (round down)
a2 // a1

In [ ]:
# elevado al cuadrado
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
# Modulo
a1 % 2

## Aggregation
Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
# Se puede aplicar lo mismo con numpy arrays
sum(a1)

In [ ]:
# numpy tambien tiene su propia implementacion de esto
np.sum(a1)

### Reglas
#### Use python methods (`sum()`) on python datatypes and use Numpy's methods (`np.sum()`) on numpys arrays

In [ ]:
# create a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
# para ver los primeros 10 elementos:
massive_array[:10]

#### Timelit: funcion magica de jupyter notebook para motrarte cuanto tarda en ejecutarse una linea de codigo

In [ ]:
%timeit sum(massive_array) # python's sum
%timeit np.sum(massive_array) # numpy's sum

In [ ]:
a2

In [ ]:
# Media
np.mean(a2)

In [ ]:
# maximo
np.max(a2)

In [ ]:
# minimo
np.min(a2)

In [ ]:
# desviacion estandard = a measure of how spread out a group of numbers is from the mean
np.std(a2)

In [ ]:
# Variance = measure of the average degree to wich each number is different to the main
# higher variance = wider range of numbers
# lower variance = lower range of numbers
np.var(a2)

In [ ]:
# La desviacion estandard es la raiz cuadrada de la de varianza
np.sqrt(np.var(a2))

### Demo of std and var

In [ ]:
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.mean(high_var_array),np.mean(low_var_array)

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

# Reshapeing and Transposing
Por que querriamos reformatear los arrays? porque para que los modelos de ml funcionen correctamente hay que pasarles la los arrays en forma correcta.

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
# Cuando los queriamos multiplicar no era posible porque tienen diferentes formas (shapes)
a2 * a3

### General Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when:
- they are equal, or
- one of them is 1

In [ ]:
# Entonces -> como las shapes no son iguales, la que tiene menos, se le tiene que aggregar una mas en 1
# Docstring:
# a.reshape(shape, order='C')
# Returns an array containing the same data with a new shape.
a2_reshaped = a2.reshape(2,3,1)
a2_reshaped

In [ ]:
a2_reshaped.shape

In [ ]:
# Ahora si podemos multiplicar a2 y a3
a2_reshaped * a3

#### Transpose: Intercambia las filas y columnas

In [43]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [44]:
a2.shape

(2, 3)

In [45]:
# Transpose: Intercambia las filas y columnas
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3. , 6.5]])

In [46]:
a2.T.shape

(3, 2)

In [47]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [48]:
a3.T.shape

(3, 3, 2)

### En que casos querriamos usar el traspose? -> Dot product

## Dot Product: Es otra forma de encontrar patrones entre dos sets diferentes de numeros

In [51]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [52]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [53]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [54]:
# Otra forma de multiplicar dos matrices es con dot product
# Dot Product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

#### Explicacion de como multiplicar matrices y sus usos: https://www.mathsisfun.com/algebra/matrix-multiplying.html

![](matrix-multiply-ex1b.gif)

#### Importante! La cantidad de columnas de la primer matriz tiene que ser igual a la cantidad de filas de la segunda.
#### Recordando la representacion de matrices: filas x columnas

In [56]:
# Para hacer andar la multiplicacion podemos usar el traspose
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [57]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [58]:
mat3 = np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot product practical example: nut butter sales

In [76]:
np.random.seed(0)
# Creo una matriz que representa la cantidad de ventas de 3 productos los (filas) 5 dias habiles de la semana (columnas) 
sales_amounts = np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [77]:
# Para representarlo graficamente uso pandas:
weekly_sales = pd.DataFrame(sales_amounts,
                           index=["Mon","Tues","Wed","Thurs","Fry"],
                           columns=["Almond butter","Peanut Butter","Cashew Butter"])
weekly_sales

Almond butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fry                1              6              7

In [78]:
# Ahora creo el array con los precios
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [79]:
prices.shape

(3,)

In [80]:
# Create butter prices dataframe
butter_prices = pd.DataFrame(prices.reshape((1,3)),
                            index=["Price"],
                            columns=["Almond butter","Peanut Butter","Cashew Butter"])
butter_prices

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [81]:
# Ahora quiero calcular el total ebtenido en ventas cada dia
total_sales = prices.dot(sales_amounts)
total_sales

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [83]:
# Shapes aren't align. Let transpose:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [87]:
# Create daily sales con pandas:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [86]:
weekly_sales.T.shape

(3, 5)

In [89]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fry
Price  240   138  458    232  142

In [91]:
daily_sales.shape

(1, 5)

In [92]:
weekly_sales.shape

(5, 3)

In [90]:
# Para mostrarlo en la parte derecha del dataFrame
# Primero agrego una nueva columna a la matriz de weekly_sales
# Esto no anda ya que daily sales tiene 1 sola fila y deberia tener 5
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Wrong number of items passed 5, placement implies 1

In [93]:
# Le aplico traspose a daily sales para que tenga 5 filas y 1 columna
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fry                1              6              7        142