# Impontando numpy

In [1]:
import numpy as np

# Data types and attributes

## El principal tipo de dato de NumPy es ndarray.
Todo lo que usemos en numpy va a ser un ndarray (n dimensional array)

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.0]
               ,[4,5,6.5]])

a3 = np.array([[[1,2,3]
                ,[4,5,6]
                ,[7,8,9]]
               ,[[10,11,12]
                ,[13,14,15]
                ,[16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](anatomia-de-nparray.png)

In [8]:
# Con shape vemos la forma, la cantidad de elementos en cada una de sus dimensiones
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# Con ndim vemos el numero de dimenciones del ndarray
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
# Con dtype vemos el tipo de los elementos que contiene
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
# size nos dice la cantidad de elementos totales en nuestro array
a1.size, a2.size, a3.size

(3, 6, 18)

# IMPORTANTE!!! todo se trabaja con ndarray.
Los tipos de elementos adentro puede cambiar pero las manipulaciones se hacen a los ndarrays.

## Ej: Create a DataFrame from a NumPy array
Por debajo de pandas funciona numpy. Por lo que se pueden representar los ndarray con formato con pandas

In [14]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
# NOTA con Shift+Tab le dice q jupyter que habra el docstring de la funcion
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[5, 6, 6, 3, 7],
       [9, 3, 7, 1, 7],
       [7, 0, 2, 2, 4]])

In [23]:
np.random.random(size=(3,5))

array([[0.05472172, 0.28169791, 0.43708702, 0.8377954 , 0.78611726],
       [0.20884638, 0.25269675, 0.69149018, 0.86109242, 0.89833758],
       [0.11240623, 0.75924419, 0.1329308 , 0.93238304, 0.38989611]])

In [24]:
random_array_3 = np.random.rand(3,5)
random_array_3

array([[0.04447123, 0.58110932, 0.78116462, 0.22246955, 0.72127207],
       [0.44691664, 0.33269658, 0.76581693, 0.33851497, 0.30528208],
       [0.73575218, 0.458601  , 0.87776648, 0.13908298, 0.50233151]])