# Impontando numpy

In [1]:
import numpy as np

# Data types and attributes

## El principal tipo de dato de NumPy es ndarray.
Todo lo que usemos en numpy va a ser un ndarray (n dimensional array)

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.0]
               ,[4,5,6.5]])

a3 = np.array([[[1,2,3]
                ,[4,5,6]
                ,[7,8,9]]
               ,[[10,11,12]
                ,[13,14,15]
                ,[16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](anatomia-de-nparray.png)

In [7]:
# Con shape vemos la forma, la cantidad de elementos en cada una de sus dimensiones
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# Con ndim vemos el numero de dimenciones del ndarray
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
# Con dtype vemos el tipo de los elementos que contiene
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
# size nos dice la cantidad de elementos totales en nuestro array
a1.size, a2.size, a3.size

(3, 6, 18)

# IMPORTANTE!!! todo se trabaja con ndarray.
Los tipos de elementos adentro puede cambiar pero las manipulaciones se hacen a los ndarrays.

## Ej: Create a DataFrame from a NumPy array
Por debajo de pandas funciona numpy. Por lo que se pueden representar los ndarray con formato con pandas

In [13]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2. Creating arrays

In [14]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [15]:
# NOTA con Shift+Tab le dice q jupyter que habra el docstring de la funcion
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[8, 1, 3, 3, 1],
       [1, 6, 8, 0, 6],
       [0, 8, 3, 6, 7]])

In [20]:
np.random.random(size=(3,5))

array([[0.95168797, 0.77435953, 0.67894217, 0.10672463, 0.45063599],
       [0.93058805, 0.2758127 , 0.37201211, 0.16238435, 0.52913353],
       [0.69001215, 0.61697372, 0.94138897, 0.01087361, 0.28334398]])

In [21]:
random_array_3 = np.random.rand(3,5)
random_array_3

array([[0.26219749, 0.66420479, 0.85774556, 0.66231794, 0.93949023],
       [0.69965159, 0.22391295, 0.32181897, 0.99194954, 0.02147229],
       [0.79794455, 0.2330594 , 0.77341246, 0.17451722, 0.22752079]])

### Los numeros random de np son pseudo-random. Si le seteamos una semilla podemos generar numeros aleatorios reproducibles. Por si queremos reproducir las pruebas con los mismos numeros

In [26]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

# 3. Viewing arrays and matrices

In [29]:
# Para encontrar los numeros unicos en un array
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a1[0]

1

In [34]:
a2[0]

array([1., 2., 3.])

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Se puede usar slicing con arrays

In [38]:
# Si quiero los primeros dos elementos de linea, columna, array
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [42]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[4, 3, 6, 9, 8],
         [0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6]],

        [[5, 7, 8, 8, 9],
         [2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6]],

        [[5, 7, 0, 8, 4],
         [6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9]]],


       [[[9, 9, 7, 3, 2],
         [3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2]],

        [[5, 5, 0, 8, 1],
         [1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1]],

        [[2, 1, 4, 2, 5],
         [5, 5, 2, 5, 7],
         [7, 6, 1, 6, 7],
         [2, 3, 1, 9, 5]]]])

In [43]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

### Numpy arma los arrays de afuera para adentro. 
#### El la primer forma (2) sera el primer corchete -> habra dos elementos que contengan la cantidad de elementos que vengan en el siguiente campo (3).
#### El de mas a la derecha sera la dimension del elemento mas interno. En este caso un array de 5 numeros.

In [44]:
# Como obtengo los primeros 4 numeros del array mas interno:
a4[:,:,:,:4]

array([[[[4, 3, 6, 9],
         [0, 8, 5, 9],
         [9, 6, 5, 3],
         [8, 0, 4, 9]],

        [[5, 7, 8, 8],
         [2, 8, 6, 6],
         [1, 6, 8, 8],
         [2, 3, 6, 3]],

        [[5, 7, 0, 8],
         [6, 5, 8, 2],
         [9, 7, 5, 3],
         [5, 3, 3, 7]]],


       [[[9, 9, 7, 3],
         [3, 9, 7, 7],
         [1, 2, 2, 8],
         [5, 8, 4, 0]],

        [[5, 5, 0, 8],
         [1, 0, 3, 8],
         [4, 4, 0, 9],
         [7, 3, 2, 1]],

        [[2, 1, 4, 2],
         [5, 5, 2, 5],
         [7, 6, 1, 6],
         [2, 3, 1, 9]]]])